apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-max-pods
spec:
  kubeletConfig:
    maxPods: 500
    podsPerCore: 15
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: "large-pods-num"